import { BadgeCheck, ShieldCheck, UserCheck, UserX } from "lucide-react";
import { useCallback, useEffect, useState } from "react";

export default function OperatorApprovals({ apiBaseUrl, token }) {
  const [users, setUsers] = useState([]);
  const [message, setMessage] = useState("");
  const load = useCallback(() => fetch(`${apiBaseUrl}/api/operator/pending-accounts`, { headers: { Authorization: `Bearer ${token}` }, cache: "no-store" }).then((response) => response.json()).then((data) => setUsers(data.users || [])).catch(() => setMessage("Approval service unavailable")), [apiBaseUrl, token]);
  useEffect(() => { load(); const timer = setInterval(load, 5000); return () => clearInterval(timer); }, [load]);
  const decide = async (id, approve) => { const response = await fetch(`${apiBaseUrl}/api/operator/accounts/${id}/decision`, { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ approve }) }); if (response.ok) { setMessage(approve ? "Account approved" : "Account rejected"); load(); } };
  return <section className="panel approvals-panel" id="account-approvals"><div className="panel-header"><div><h2>Department Account Verification</h2><p>Approve Police, Fire, Rescue and Hospital registrations</p></div><span className="approval-count"><ShieldCheck size={14} /> {users.length} pending</span></div><div className="approval-list">{users.map((user) => <article key={user.id}><div className="approval-avatar"><BadgeCheck size={19} /></div><div><strong>{user.full_name}</strong><span>{user.role} · {user.official_details?.designation || user.official_details?.hospital_type || "Official account"}</span><small>{user.official_details?.department || user.official_details?.hospital_id || "Registration details supplied"} · {user.location}</small></div><div className="approval-actions"><button className="approve" onClick={() => decide(user.id, true)}><UserCheck size={14} /> Approve</button><button onClick={() => decide(user.id, false)}><UserX size={14} /> Reject</button></div></article>)}{!users.length && <p className="approval-empty">No department accounts are waiting for approval.</p>}</div>{message && <p className="approval-message">{message}</p>}</section>;
}
